version: '3.9'

volumes:
  postgres_data:
  redis_data:

services:
  postgres:
    restart: unless-stopped
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - ${DB_PORT}

  redis:
    restart: unless-stopped
    image: redis:7.2.4-alpine
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/var/lib/redis/data
    expose:
     - ${REDIS_PORT}

  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: sh /app/run-server.sh
    # environment:
    #   - DJANGO_ALLOWED_HOSTS=localhost,backend,172.22.0.4
    #   - DJANGO_CORS_ALLOWED_ORIGINS=http://localhost:8000,http://localhost:5173,http://backend:8000,http://172.22.0.4:8000
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - 3000:3000
