# Generated by Django 5.0.2 on 2024-03-03 09:46

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Art",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="arts/images", verbose_name="Изображение"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=10000, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "for_sale",
                    models.BooleanField(default=False, verbose_name="На продажу"),
                ),
                (
                    "views",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Тэги",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arts",
                        related_query_name="art",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Арт",
                "verbose_name_plural": "Арты",
            },
        ),
        migrations.CreateModel(
            name="ArtComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(max_length=4096, verbose_name="Текст комментария"),
                ),
                (
                    "art",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arts.art",
                        verbose_name="Арт",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="art",
            name="comments",
            field=models.ManyToManyField(
                related_name="commented_arts",
                related_query_name="commented_art",
                through="arts.ArtComment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Комментарии",
            ),
        ),
        migrations.CreateModel(
            name="ArtLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "art",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arts.art",
                        verbose_name="Арт",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="art",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_arts",
                related_query_name="liked_art",
                through="arts.ArtLike",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Лайки",
            ),
        ),
        migrations.AddConstraint(
            model_name="artlike",
            constraint=models.UniqueConstraint(
                fields=("user", "art"), name="unique_user_art"
            ),
        ),
        migrations.AddIndex(
            model_name="art",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["tags"], name="arts_art_tags_2ef9de_gin"
            ),
        ),
    ]
