# Generated by Django 5.0.3 on 2024-05-05 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_type",
                    models.CharField(
                        choices=[
                            ("group", "Групповой чат"),
                            ("personal", "Личный чат"),
                        ],
                        default="personal",
                        verbose_name="Тип чата",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чат",
                "verbose_name_plural": "Чаты",
            },
        ),
        migrations.CreateModel(
            name="ChatMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата присоединения к чату"
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_members",
                        related_query_name="chat_member",
                        to="chats.chat",
                        verbose_name="Чат",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_members",
                        related_query_name="user_member",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник чата",
                "verbose_name_plural": "Участники чата",
            },
        ),
        migrations.AddField(
            model_name="chat",
            name="users",
            field=models.ManyToManyField(
                related_name="chats",
                related_query_name="chat",
                through="chats.ChatMember",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участники чата",
            ),
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(max_length=8192, verbose_name="Текст сообщения"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания сообщения"
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        related_query_name="chat_message",
                        to="chats.chat",
                        verbose_name="Чат",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_messages",
                        related_query_name="member_message",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение чата",
                "verbose_name_plural": "Сообщения чатов",
            },
        ),
        migrations.CreateModel(
            name="GroupChatData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название чата"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="chats/groups",
                        verbose_name="Аватар группы",
                    ),
                ),
                (
                    "chat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_chat_data",
                        related_query_name="group_chat_data",
                        to="chats.chat",
                        verbose_name="Чат",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalChatData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_chat_data",
                        related_query_name="personal_chat_data",
                        to="chats.chat",
                        verbose_name="Чат",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="chatmember",
            constraint=models.UniqueConstraint(
                fields=("chat", "user"), name="chatmember_chat_user_unique"
            ),
        ),
    ]
