# Generated by Django 5.0.3 on 2024-05-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmember",
            name="read_before",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата и время, до куда пользователь дочитал историю чата",
            ),
        ),
    ]
